apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ws-dev
  name: xentask-login-ingress
  annotations:
    field.cattle.io/creatorId: cwolsen
    nginx.ingress.kubernetes.io/proxy-body-size: 256m
spec:
  ingressClassName: nginx
  rules:
  - host: xentask-login.dev.your-domain.com
    http:
      paths:
      - backend:
          service:
             name: xentask-login
             port:
               number: 8080
        path: /
        pathType: ImplementationSpecific
  tls:
    - hosts:
      - xentask-login.dev.your-domain.com
      secretName: tls-wildcard-your-domain-dev
status:
  loadBalancer:
    ingress:
      - hostname: kube-001.your-domain.com
      - hostname: kube-002.your-domain.com
      - hostname: kube-003.your-domain.com
      - hostname: kube-004.your-domain.com
      - hostname: kube-005.your-domain.com
