apiVersion: v1
kind: Service
metadata:
    name: xentask-admin-svc
    namespace: live-prod
spec:
    selector:
      app: xentask-admin
    ports:
     - name: xentask-admin
       protocol: TCP
       port: 8080
       targetPort: 8080