apiVersion: v1
kind: Service
metadata:
    name: xentask-forms-api-svc
    namespace: ws-prod
spec:
    selector:
      app: xentask-forms-api
    ports:
     - name: xentask-forms-api
       protocol: TCP
       port: 8080
       targetPort: 8080