apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: cwolsen
  labels:
    workload.user.cattle.io/workloadselector: deployment-live-dev-xentask-forms
  name: xentask-forms
  namespace: live-dev
  selfLink: /apis/apps/v1/namespaces/live-dev/deployments/xentask-forms
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-live-dev-xentask-forms
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"xentask-forms","hostPort":0,"kind":"ClusterIP","name":"8080tcp02","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-live-dev-xentask-forms
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values: [ "amd64","arm64" ]
      containers:
      - env:
        - name: DEPLOY_ENV
          value: "DEV"
        - name: API_HOST
          value: "xentask-api.dev.your-domain.com"
        - name: LOGIN_HOST
          value: "xentask-login.dev.your-domain.com"
        image: ghcr.io/your-org/xentask/xentask-forms:dev
        imagePullPolicy: Always
        name: xentask-forms
        ports:
        - containerPort: 8080
          name: 8080tcp02
          protocol: TCP
        - containerPort: 8080
          name: 8080tcp300801
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /fpm-ping
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /logs
          name: logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /logs
          type: DirectoryOrCreate
        name: logs
